name: Release 4.x

on: [push]

jobs:
  build:
    runs-on:  ubuntu-latest
    name: Create Release

    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          ref: v4.x

      - name: Move License
        shell: bash
        run: |
          mv LICENSE.md README.md ${{ github.workspace }}/addons/VisualShaderExtras

      - name: Directory info
        shell: bash
        run: |
          pwd
          ls -R

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.repository.name }}
          path: |
            ${{ github.workspace }}/addons/VisualShaderExtras/*

      - name: Directory info
        shell: bash
        run: |
          pwd
          ls

      - name: Zip the folder
        uses: vimtor/action-zip@v1.1
        with:
          files: addons/VisualShaderExtras/
          dest: VisualShaderExtras-4.0.zip

      - name: Directory info
        shell: bash
        run: |
          pwd
          ls

      - name: Upload zip to release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "VisualShaderExtras-4.0.zip"
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')