name: Release

on:
  push:
    branches:
      - '3.x'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ASSET_LIB_USERNAME: flamelizard
  ASSET_LIB_PASSSWORD: ${{ secrets.ASSET_STORE_PASSWORD }}
  ASSET_LIB_ASSET_ID: 1538

jobs:
  prerelease:
      if: "github.event.head_commit.message != 'Release preparation: storing Version and Changelog'"
      name: Preparing release
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v3
            with:
              fetch-depth: 0
              token: ${{ secrets.PAT }}

          - name: Calculate version
            id: calculate_version
            uses: mathieudutour/github-tag-action@v6.0
            with:
              tag_prefix: ""
              github_token: ${{ secrets.PAT }}
              dry_run: true
              default_bump: false

          - name: "Write changelog"
            run: |
              CHANGELOG=""
              if [ -e addons/VisualShaderExtras/AddonAssets/CHANGELOG.md ]
              then
                  CHANGELOG=$(cat addons/VisualShaderExtras/AddonAssets/CHANGELOG.md)
              fi
              echo -e "${{steps.calculate_version.outputs.changelog}}\n\n${CHANGELOG}" > addons/VisualShaderExtras/AddonAssets/CHANGELOG.md
            if: github.ref == 'refs/heads/3.x' && steps.calculate_version.outputs.new_version != ''

          - name: "Commit"
            uses: EndBug/add-and-commit@v7.2.1
            with:
              message: 'Release preparation: storing Version and Changelog'
              push: true
            if: steps.calculate_version.outputs.new_version != ''

  release:
      # Create release only after the version was bumped and release notes added:
    if: "github.event.head_commit.message == 'Release preparation: storing Version and Changelog'"
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Create version
        id: create_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          tag_prefix: ""
          dry_run: ${{ github.ref_name != '3.x' }}
          github_token: ${{ secrets.PAT }}
          default_bump: false

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: VisualShaderExtras-${{ steps.create_version.outputs.new_tag }}
          path: addons/VisualShaderExtras/
          if-no-files-found: error # 'warn' or 'ignore' are also available, defaults to `warn`
        if: steps.create_version.outputs.new_version != ''

      - uses: ncipollo/release-action@v1
        with:
          name: ${{ steps.create_version.outputs.new_tag }}
          draft: false
          prerelease: ${{ github.ref_name != '3.x' }}
          artifacts: ""
          replacesArtifacts: false
          generateReleaseNotes: true
          token: ${{ secrets.PAT }}
          tag: ${{ steps.create_version.outputs.new_tag }}
        if: steps.create_version.outputs.new_version != ''

  assetlib:
    if: "github.ref == 'refs/heads/3.x' && github.event.head_commit.message == 'Release preparation: storing Version and Changelog'"
    runs-on: ubuntu-latest
    needs: release
    name: Godot AssetLib
    steps:

      - uses: actions/checkout@v3

      -   name: Calculate version
          id: calculate_version
          uses: mathieudutour/github-tag-action@v6.0
          with:
              tag_prefix: "v"
              github_token: ${{ secrets.PAT }}
              dry_run: true
              default_bump: false

      - name: Set Version
        run: |
            echo "version=${{ steps.calculate_version.outputs.previous_tag }}" >> $GITHUB_ENV
      - name: Godot Asset Lib
        uses: deep-entertainment/godot-asset-lib-action@v0.4.0
        with:
          username: ${{ env.ASSET_LIB_USERNAME }}
          password: ${{ env.ASSET_LIB_PASSSWORD }}
          assetId: ${{ env.ASSET_LIB_ASSET_ID }}